name: Flutter Build APK
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.1'
          channel: 'stable'
      
      - name: Clean and get dependencies
        run: |
          flutter clean
          flutter pub get
        
      - name: Analyze code
        run: flutter analyze --no-fatal-infos
        continue-on-error: true
        
      - name: Build APK
        run: |
          BUILD_DATE=$(date +%y%m%d)
          flutter build apk --release --build-name=0.0.0.6 --build-number=6 --no-shrink
          cd build/app/outputs/flutter-apk
          ls -la
          mv app-release.apk ${BUILD_DATE}-rb-apk-ver0.0.0.6.apk
          
      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: routine-buddy-apk
          path: build/app/outputs/flutter-apk/*-rb-apk-ver*.apk
          retention-days: 30
